[workspace]
members = [
    "backend",
    "frontend",
    "common",
]

[workspace.dependencies]
log = "0.4"
env_logger = "0.11"
serde = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
